<?php

declare(strict_types=1);

use Migrations\AbstractSeed;

/**
 * Menus seed.
 */
class MenusSeed extends AbstractSeed
{
    /**
     * Run Method.
     *
     * Write your database seeder using this method.
     *
     * More information on writing seeds is available here:
     * https://book.cakephp.org/phinx/0/en/seeding.html
     *
     * @return void
     */
    public function run()
    {
        $data = [
            [
                'id' => 9,
                'active' => true,
                'divider' => false,
                'admin_menu' => false,
                'name' => 'Labels',
                'description' => 'Label Printing',
                'url' => null,
                'title' => '',
                'parent_id' => null,
                'lft' => 13,
                'rght' => 26,
                'modified' => '2016-08-31 19:41:20',
                'created' => '2015-03-25 23:12:20',
                'bs_url' => '',
                'extra_args' => '',
            ],
            [
                'id' => 10,
                'active' => true,
                'divider' => false,
                'admin_menu' => false,
                'name' => 'Warehouse',
                'description' => 'Top Level Menu for Warehous',
                'url' => null,
                'title' => '',
                'parent_id' => null,
                'lft' => 27,
                'rght' => 44,
                'modified' => '2015-04-03 14:43:49',
                'created' => '2015-03-25 23:12:39',
                'bs_url' => '',
                'extra_args' => '',
            ],
            [
                'id' => 12,
                'active' => true,
                'divider' => false,
                'admin_menu' => false,
                'name' => 'Reporting',
                'description' => 'Reporting top level menu',
                'url' => '',
                'title' => '',
                'parent_id' => null,
                'lft' => 1,
                'rght' => 4,
                'modified' => '2020-06-22 10:42:02',
                'created' => '2015-03-25 23:12:58',
                'bs_url' => '',
                'extra_args' => '',
            ],
            [
                'id' => 13,
                'active' => true,
                'divider' => false,
                'admin_menu' => false,
                'name' => 'Items',
                'description' => 'Item data view',
                'url' => null,
                'title' => '',
                'parent_id' => 100,
                'lft' => 6,
                'rght' => 7,
                'modified' => '2019-10-15 18:19:06',
                'created' => '2015-03-25 23:13:26',
                'bs_url' => 'Items::index',
                'extra_args' => '',
            ],
            [
                'id' => 14,
                'active' => true,
                'divider' => false,
                'admin_menu' => false,
                'name' => 'Locations',
                'description' => 'Locations view',
                'url' => null,
                'title' => '',
                'parent_id' => 36,
                'lft' => 62,
                'rght' => 63,
                'modified' => '2019-10-15 18:03:22',
                'created' => '2015-03-25 23:14:23',
                'bs_url' => 'Locations::index',
                'extra_args' => '',
            ],
            [
                'id' => 15,
                'active' => true,
                'divider' => false,
                'admin_menu' => false,
                'name' => 'Inventory Statuses',
                'description' => 'List Inventory Statuses',
                'url' => null,
                'title' => 'List Inventory Statuses',
                'parent_id' => 36,
                'lft' => 58,
                'rght' => 59,
                'modified' => '2019-10-15 18:05:00',
                'created' => '2015-03-25 23:15:07',
                'bs_url' => 'InventoryStatuses::index',
                'extra_args' => '',
            ],
            [
                'id' => 25,
                'active' => true,
                'divider' => false,
                'admin_menu' => false,
                'name' => 'Reprint',
                'description' => '',
                'url' => null,
                'title' => 'Reprint Pallet Label',
                'parent_id' => 9,
                'lft' => 20,
                'rght' => 21,
                'modified' => '2020-04-02 04:51:35',
                'created' => '2015-03-26 06:16:27',
                'bs_url' => 'Pallets::lookup',
                'extra_args' => '',
            ],
            [
                'id' => 28,
                'active' => true,
                'divider' => false,
                'admin_menu' => false,
                'name' => 'View Stock',
                'description' => '',
                'url' => null,
                'title' => '',
                'parent_id' => 10,
                'lft' => 30,
                'rght' => 31,
                'modified' => '2020-04-03 21:49:00',
                'created' => '2015-03-26 06:18:24',
                'bs_url' => 'Pallets::onhand',
                'extra_args' => '',
            ],
            [
                'id' => 29,
                'active' => false,
                'divider' => false,
                'admin_menu' => false,
                'name' => 'Put-away',
                'description' => '',
                'url' => '',
                'title' => '',
                'parent_id' => 10,
                'lft' => 28,
                'rght' => 29,
                'modified' => '2020-06-22 17:17:06',
                'created' => '2015-03-26 06:18:45',
                'bs_url' => 'Pallets::unassignedPallets',
                'extra_args' => '',
            ],
            [
                'id' => 30,
                'active' => true,
                'divider' => false,
                'admin_menu' => false,
                'name' => 'Dispatch',
                'description' => '',
                'url' => '',
                'title' => 'View/Edit Shipments and Print Shippers',
                'parent_id' => null,
                'lft' => 53,
                'rght' => 54,
                'modified' => '2020-06-22 17:19:53',
                'created' => '2015-03-26 06:19:14',
                'bs_url' => 'Shipments::index',
                'extra_args' => '',
            ],
            [
                'id' => 36,
                'active' => true,
                'divider' => false,
                'admin_menu' => true,
                'name' => 'Setup',
                'description' => 'Setup Menu',
                'url' => '',
                'title' => 'Admin Menu',
                'parent_id' => null,
                'lft' => 55,
                'rght' => 84,
                'modified' => '2020-06-26 17:13:09',
                'created' => '2015-03-27 16:40:55',
                'bs_url' => '',
                'extra_args' => '',
            ],
            [
                'id' => 38,
                'active' => true,
                'divider' => false,
                'admin_menu' => false,
                'name' => 'Pallet Track',
                'description' => '',
                'url' => null,
                'title' => 'Track a pallet',
                'parent_id' => 10,
                'lft' => 38,
                'rght' => 39,
                'modified' => '2020-04-03 02:34:46',
                'created' => '2015-03-27 16:55:25',
                'bs_url' => 'Pallets::lookup',
                'extra_args' => '',
            ],
            [
                'id' => 39,
                'active' => true,
                'divider' => false,
                'admin_menu' => false,
                'name' => 'Settings',
                'description' => 'View Settings',
                'url' => null,
                'title' => 'View and change configuration settings',
                'parent_id' => 36,
                'lft' => 76,
                'rght' => 77,
                'modified' => '2018-09-05 13:06:22',
                'created' => '2015-03-27 19:46:28',
                'bs_url' => 'Settings::index',
                'extra_args' => '',
            ],
            [
                'id' => 46,
                'active' => true,
                'divider' => false,
                'admin_menu' => false,
                'name' => 'Menus',
                'description' => 'List Menus',
                'url' => null,
                'title' => '',
                'parent_id' => 36,
                'lft' => 78,
                'rght' => 79,
                'modified' => '2018-09-05 13:02:04',
                'created' => '2015-03-28 23:08:36',
                'bs_url' => 'Menus::index',
                'extra_args' => '',
            ],
            [
                'id' => 57,
                'active' => false,
                'divider' => false,
                'admin_menu' => false,
                'name' => 'Shipments',
                'description' => '',
                'url' => null,
                'title' => '',
                'parent_id' => 119,
                'lft' => 46,
                'rght' => 47,
                'modified' => '2016-09-01 09:36:23',
                'created' => '2015-03-29 21:34:45',
                'bs_url' => '',
                'extra_args' => '',
            ],
            [
                'id' => 96,
                'active' => false,
                'divider' => false,
                'admin_menu' => false,
                'name' => 'Pallet Labels',
                'description' => 'Print Pallet Labels',
                'url' => null,
                'title' => 'Pallet Labels',
                'parent_id' => 9,
                'lft' => 14,
                'rght' => 15,
                'modified' => '2016-08-31 20:18:44',
                'created' => '2015-10-21 09:57:23',
                'bs_url' => '',
                'extra_args' => '',
            ],
            [
                'id' => 99,
                'active' => true,
                'divider' => false,
                'admin_menu' => false,
                'name' => 'Pallet Label with Date',
                'description' => 'Print a label and select the production date',
                'url' => '',
                'title' => 'Print custom labels - for short or sample runs',
                'parent_id' => 9,
                'lft' => 18,
                'rght' => 19,
                'modified' => '2020-07-13 20:48:52',
                'created' => '2015-10-21 10:04:51',
                'bs_url' => 'Pallets::palletPrintWithProductionDate',
                'extra_args' => '',
            ],
            [
                'id' => 100,
                'active' => true,
                'divider' => false,
                'admin_menu' => false,
                'name' => 'Data',
                'description' => 'Data Menu',
                'url' => null,
                'title' => 'Item Data etc',
                'parent_id' => null,
                'lft' => 5,
                'rght' => 12,
                'modified' => '2016-04-18 20:47:59',
                'created' => '2016-04-18 20:47:59',
                'bs_url' => '',
                'extra_args' => '',
            ],
            [
                'id' => 101,
                'active' => true,
                'divider' => false,
                'admin_menu' => false,
                'name' => 'Day of Year',
                'description' => 'Day of Year Calculator',
                'url' => null,
                'title' => 'Day of Year Number Calculator',
                'parent_id' => 100,
                'lft' => 10,
                'rght' => 11,
                'modified' => '2020-04-02 03:34:22',
                'created' => '2016-04-18 20:52:01',
                'bs_url' => 'PrintLabels::dayOfYear',
                'extra_args' => 'dayofyear',
            ],
            [
                'id' => 108,
                'active' => true,
                'divider' => false,
                'admin_menu' => false,
                'name' => 'Users',
                'description' => 'List Users',
                'url' => null,
                'title' => '',
                'parent_id' => 36,
                'lft' => 56,
                'rght' => 57,
                'modified' => '2018-09-05 13:04:23',
                'created' => '2016-08-31 14:21:28',
                'bs_url' => 'Users::index',
                'extra_args' => '',
            ],
            [
                'id' => 112,
                'active' => false,
                'divider' => true,
                'admin_menu' => false,
                'name' => 'Tracing',
                'description' => '',
                'url' => null,
                'title' => '',
                'parent_id' => 10,
                'lft' => 36,
                'rght' => 37,
                'modified' => '2016-08-31 22:15:49',
                'created' => '2016-08-31 22:15:28',
                'bs_url' => '',
                'extra_args' => '',
            ],
            [
                'id' => 119,
                'active' => false,
                'divider' => false,
                'admin_menu' => false,
                'name' => 'Dispatch',
                'description' => 'Dispatch Menu',
                'url' => '',
                'title' => 'Dispatch Menu',
                'parent_id' => null,
                'lft' => 45,
                'rght' => 52,
                'modified' => '2020-06-22 17:19:32',
                'created' => '2016-09-01 09:32:47',
                'bs_url' => '',
                'extra_args' => '',
            ],
            [
                'id' => 121,
                'active' => false,
                'divider' => true,
                'admin_menu' => false,
                'name' => 'Utilities',
                'description' => 'Utilities',
                'url' => null,
                'title' => 'Utilities',
                'parent_id' => 100,
                'lft' => 8,
                'rght' => 9,
                'modified' => '2016-09-01 10:12:02',
                'created' => '2016-09-01 10:10:48',
                'bs_url' => '',
                'extra_args' => '',
            ],
            [
                'id' => 129,
                'active' => true,
                'divider' => false,
                'admin_menu' => false,
                'name' => 'Edit QA Status',
                'description' => 'Edit QA Status',
                'url' => null,
                'title' => '',
                'parent_id' => 10,
                'lft' => 42,
                'rght' => 43,
                'modified' => '2020-04-04 11:39:13',
                'created' => '2016-12-05 17:09:10',
                'bs_url' => 'Pallets::bulkStatusRemove',
                'extra_args' => '3',
            ],
            [
                'id' => 130,
                'active' => false,
                'divider' => true,
                'admin_menu' => false,
                'name' => 'QA',
                'description' => 'QA',
                'url' => null,
                'title' => '',
                'parent_id' => 10,
                'lft' => 40,
                'rght' => 41,
                'modified' => '2016-12-05 17:24:32',
                'created' => '2016-12-05 17:24:32',
                'bs_url' => '',
                'extra_args' => '',
            ],
            [
                'id' => 135,
                'active' => true,
                'divider' => false,
                'admin_menu' => false,
                'name' => 'Shift Report',
                'description' => 'Shift Report',
                'url' => null,
                'title' => '',
                'parent_id' => 12,
                'lft' => 2,
                'rght' => 3,
                'modified' => '2019-12-13 11:41:10',
                'created' => '2017-04-07 22:22:10',
                'bs_url' => 'Pallets::shiftReport',
                'extra_args' => '',
            ],
            [
                'id' => 141,
                'active' => true,
                'divider' => false,
                'admin_menu' => false,
                'name' => 'Product Types',
                'description' => 'Product Types',
                'url' => null,
                'title' => '',
                'parent_id' => 36,
                'lft' => 60,
                'rght' => 61,
                'modified' => '2018-09-05 12:59:46',
                'created' => '2018-09-05 12:59:46',
                'bs_url' => 'ProductTypes::index',
                'extra_args' => '',
            ],
            [
                'id' => 142,
                'active' => true,
                'divider' => false,
                'admin_menu' => true,
                'name' => 'Shifts',
                'description' => 'Shifts',
                'url' => null,
                'title' => '',
                'parent_id' => 36,
                'lft' => 64,
                'rght' => 65,
                'modified' => '2018-09-05 13:00:42',
                'created' => '2018-09-05 13:00:42',
                'bs_url' => 'Shifts::index',
                'extra_args' => '',
            ],
            [
                'id' => 143,
                'active' => true,
                'divider' => false,
                'admin_menu' => false,
                'name' => 'Print Templates',
                'description' => 'Print Templates',
                'url' => null,
                'title' => '',
                'parent_id' => 36,
                'lft' => 72,
                'rght' => 73,
                'modified' => '2018-09-05 13:01:24',
                'created' => '2018-09-05 13:01:24',
                'bs_url' => 'PrintTemplates::index',
                'extra_args' => '',
            ],
            [
                'id' => 144,
                'active' => true,
                'divider' => true,
                'admin_menu' => false,
                'name' => 'Label Chooser',
                'description' => 'Label Chooser',
                'url' => '',
                'title' => 'Label Chooser',
                'parent_id' => 9,
                'lft' => 24,
                'rght' => 25,
                'modified' => '2020-06-19 16:21:10',
                'created' => '2018-10-23 11:40:52',
                'bs_url' => 'PrintLog::labelChooser',
                'extra_args' => '',
            ],
            [
                'id' => 145,
                'active' => false,
                'divider' => true,
                'admin_menu' => false,
                'name' => 'Custom Label Printing',
                'description' => 'Chooser',
                'url' => null,
                'title' => '',
                'parent_id' => 9,
                'lft' => 22,
                'rght' => 23,
                'modified' => '2019-06-18 22:27:35',
                'created' => '2018-11-05 12:07:21',
                'bs_url' => '',
                'extra_args' => '',
            ],
            [
                'id' => 146,
                'active' => true,
                'divider' => false,
                'admin_menu' => false,
                'name' => 'Location Usage',
                'description' => 'Location Usage',
                'url' => null,
                'title' => 'Marg Location Usage',
                'parent_id' => 10,
                'lft' => 34,
                'rght' => 35,
                'modified' => '2020-04-04 22:24:29',
                'created' => '2018-12-10 10:24:45',
                'bs_url' => 'Pallets::locationSpaceUsage',
                'extra_args' => '',
            ],
            [
                'id' => 147,
                'active' => false,
                'divider' => false,
                'admin_menu' => false,
                'name' => 'Pick Stock',
                'description' => 'Pick Stock',
                'url' => '',
                'title' => 'Pick Stock',
                'parent_id' => 119,
                'lft' => 50,
                'rght' => 51,
                'modified' => '2020-06-22 17:18:21',
                'created' => '2018-12-14 23:36:49',
                'bs_url' => 'Shipments::pickStock',
                'extra_args' => '',
            ],
            [
                'id' => 148,
                'active' => false,
                'divider' => false,
                'admin_menu' => false,
                'name' => 'Pick',
                'description' => 'Pick',
                'url' => null,
                'title' => '',
                'parent_id' => 119,
                'lft' => 48,
                'rght' => 49,
                'modified' => '2018-12-15 00:51:57',
                'created' => '2018-12-15 00:50:35',
                'bs_url' => '',
                'extra_args' => '',
            ],
            [
                'id' => 150,
                'active' => true,
                'divider' => false,
                'admin_menu' => false,
                'name' => 'Pack Sizes',
                'description' => 'Pack Sizes',
                'url' => null,
                'title' => 'Pack Sizes',
                'parent_id' => 36,
                'lft' => 66,
                'rght' => 67,
                'modified' => '2019-10-15 17:35:22',
                'created' => '2019-10-12 20:04:35',
                'bs_url' => 'PackSizes::index',
                'extra_args' => '',
            ],
            [
                'id' => 152,
                'active' => true,
                'divider' => false,
                'admin_menu' => false,
                'name' => 'Pallet Label Print',
                'description' => 'Pallet Print',
                'url' => '',
                'title' => 'Pallet Print',
                'parent_id' => 9,
                'lft' => 16,
                'rght' => 17,
                'modified' => '2020-06-21 19:02:53',
                'created' => '2019-10-12 21:41:15',
                'bs_url' => 'Pallets::palletPrint',
                'extra_args' => '3',
            ],
            [
                'id' => 153,
                'active' => true,
                'divider' => false,
                'admin_menu' => false,
                'name' => 'Printers',
                'description' => '',
                'url' => null,
                'title' => '',
                'parent_id' => 36,
                'lft' => 70,
                'rght' => 71,
                'modified' => '2019-10-15 17:34:35',
                'created' => '2019-10-13 08:45:45',
                'bs_url' => 'Printers::index',
                'extra_args' => '',
            ],
            [
                'id' => 155,
                'active' => true,
                'divider' => false,
                'admin_menu' => false,
                'name' => 'Production Lines',
                'description' => '',
                'url' => null,
                'title' => '',
                'parent_id' => 36,
                'lft' => 74,
                'rght' => 75,
                'modified' => '2019-10-15 17:34:15',
                'created' => '2019-10-13 08:50:06',
                'bs_url' => 'ProductionLines::index',
                'extra_args' => '',
            ],
            [
                'id' => 157,
                'active' => true,
                'divider' => true,
                'admin_menu' => true,
                'name' => 'Help',
                'description' => 'Help System',
                'url' => '',
                'title' => '',
                'parent_id' => 36,
                'lft' => 80,
                'rght' => 81,
                'modified' => '2020-04-15 00:30:27',
                'created' => '2019-10-20 16:42:43',
                'bs_url' => 'Help::index',
                'extra_args' => '',
            ],
            [
                'id' => 158,
                'active' => true,
                'divider' => false,
                'admin_menu' => true,
                'name' => 'Items',
                'description' => 'Admin Menu Items',
                'url' => null,
                'title' => 'Items',
                'parent_id' => 36,
                'lft' => 68,
                'rght' => 69,
                'modified' => '2019-10-23 12:13:08',
                'created' => '2019-10-23 12:13:08',
                'bs_url' => 'Items::index',
                'extra_args' => '',
            ],
            [
                'id' => 159,
                'active' => false,
                'divider' => true,
                'admin_menu' => true,
                'name' => 'Help',
                'description' => 'Help',
                'url' => null,
                'title' => 'Help',
                'parent_id' => 36,
                'lft' => 82,
                'rght' => 83,
                'modified' => '2019-10-23 12:15:26',
                'created' => '2019-10-23 12:15:26',
                'bs_url' => '',
                'extra_args' => '',
            ],
            [
                'id' => 160,
                'active' => true,
                'divider' => false,
                'admin_menu' => false,
                'name' => 'Mixed date / part pallets',
                'description' => '',
                'url' => '',
                'title' => 'View pallets with mixed carton dates or not full',
                'parent_id' => 10,
                'lft' => 32,
                'rght' => 33,
                'modified' => '2020-04-08 23:47:02',
                'created' => '2019-12-13 11:35:50',
                'bs_url' => 'Pallets::viewPartPalletsCartons',
                'extra_args' => '',
            ],
        ];
        
        $table = $this->table('menus');

        $table->truncate();
        
        $table->insert($data)->save();
    }
}
