export default {
  shipment: {
    operation: "",
    id: "",
    shipment_type: "",
    shipped: false,
    shipper: "",
    destination: "",
    product_type_id: "",
    labelIds: [],
  },
  isExpanded: {},
  products: [],
  productDescriptions: {},
  shipmentTypeDisabled: false,
  labelLists: {},
  loading: false,
  redirect: false,
  labelCounts: {},
  showAlert: false,
  alertTextBold: "Default Alert Bold",
  alertText: "Default alert text",
  alertVariant: "info",
  errors: {},
  operationName: "",
  isTypeAheadLoading: false,
  productType: 0,
  productTypeName: "",
  allPallets: [],
  options: [],
  productTypes: [],
  baseUrl: "",
};
